package sbnz.tta.rules.plan;

import com.tta.app.model.enums.RacketLevel;
import com.tta.app.model.racket.Racket;

rule "Calculate racket speed"
no-loop
	when
		$r: Racket($bl: blade, $frb: fhRubber, $brb: bhRubber)
	then
		Double speed = ($bl.getSpeed() + $frb.getSpeed() + $bl.getSpeed() + $brb.getSpeed()) / 4;
		modify($r) {
			setSpeed(speed);
		}
		System.out.println("Izracunata brzina reketa: " + speed);
end

rule "Calculate racket spin"
no-loop
	when
		$r: Racket($bl: blade, $frb: fhRubber, $brb: bhRubber)
	then
		Double spin = (20 - ($bl.getHardness() + $bl.getStiffness() + $bl.getHardness() + $bl.getStiffness()) / 6 + $frb.getSpin() + $brb.getSpin()) / 4;
		modify($r) {
			setSpin(spin);
		}
		System.out.println("Izracunat spin reketa: " + spin);
end

rule "Calculate racket control"
no-loop
	when
		$r: Racket($bl: blade, $frb: fhRubber, $brb: bhRubber)
	then
		Double control = ($bl.getControl() + $frb.getControl() + $bl.getControl() + $brb.getControl()) / 4;
		modify($r) {
			setControl(control);
		}
		System.out.println("Izracunata kontrola reketa: " + control);
end

// PRO
rule "Calculate racket level - PRO (speed >= 8, spin >= 8)"
no-loop
salience 0
	when
		$r: Racket(speed >= 8, spin >= 8)
	then
		modify($r) {
			setRacketLevel(RacketLevel.PRO);
		}
		System.out.println("Reket je - PRO (speed >= 8, spin >= 8)");
end

rule "Calculate racket level - PRO (speed >= 7, spin >= 9)"
no-loop
salience 0
	when
		$r: Racket(speed >= 7, spin >= 9)
	then
		modify($r) {
			setRacketLevel(RacketLevel.PRO);
		}
		System.out.println("Reket je - PRO (speed >= 7, spin >= 9)");
end

rule "Calculate racket level - PRO (speed >= 9, spin >= 7)"
no-loop
salience 0
	when
		$r: Racket(speed >= 9, spin >= 7)
	then
		modify($r) {
			setRacketLevel(RacketLevel.PRO);
		}
		System.out.println("Reket je - PRO (speed >= 9, spin >= 7)");
end


// ADVANCED
rule "Calculate racket level - ADVANCED (speed >= 7, spin >= 7)"
no-loop
salience 10
	when
		$r: Racket(speed >= 7, spin >= 7)
	then
		modify($r) {
			setRacketLevel(RacketLevel.ADVANCED);
		}
		System.out.println("Reket je - ADVANCED (speed >= 7, spin >= 7)");
end

rule "Calculate racket level - ADVANCED (speed >= 8, spin >= 6)"
no-loop
salience 10
	when
		$r: Racket(speed >= 8, spin >= 6)
	then
		modify($r) {
			setRacketLevel(RacketLevel.ADVANCED);
		}
		System.out.println("Reket je - ADVANCED (speed >= 8, spin >= 6)");
end

rule "Calculate racket level - ADVANCED (speed >= 6, spin >= 8)"
no-loop
salience 10
	when
		$r: Racket(speed >= 6, spin >= 8)
	then
		modify($r) {
			setRacketLevel(RacketLevel.ADVANCED);
		}
		System.out.println("Reket je - ADVANCED (speed >= 6, spin >= 8)");
end

// BEGINNER
rule "Calculate racket level - BEGINNER"
no-loop
salience 30
	when
		$r: Racket()
	then
		modify($r) {
			setRacketLevel(RacketLevel.BEGINNER);
		}
		System.out.println("Reket je - BEGINNER");
end