package sbnz.tta.rules;

import com.tta.app.model.User;
import com.tta.app.model.enums.TrainingExperience;

rule "Test rule"
    when
        $u: User(budget >= 100)
    then
        $u.setExperience(TrainingExperience.INTERMEDIATE);
        update($u);
end

rule "Test rule - 2"
    when
        $u: User(budget < 100)
    then
        $u.setExperience(TrainingExperience.BEGINNER);
        update($u);
end