package sbnz.tta.rules.cep;

import com.tta.app.model.events.EndTrainingEvent;
import com.tta.app.model.events.CreateGradeEvent;
import com.tta.app.model.training.Training;

rule "Create grade when training is over"
    when
		$tr: Training($id: id)
       	$endTr: EndTrainingEvent(processed == false)
    then
    	modify ($endTr) {
    	setProcessed(true);
    	};
		insert(new CreateGradeEvent($id));
    	System.out.println("Trening je završen");
end