package sbnz.tta.rules.cep;

import com.tta.app.model.events.BadSpeedEvent;
import com.tta.app.model.events.FixSpeedEvent;

rule "Two bad speeds"
    when
        $e1: BadSpeedEvent(processed == false, $tId: trainingId)
        $e2: BadSpeedEvent(processed == false, trainingId == $tId, this after [200ms, 2200ms] $e1)
    then
    modify ($e1) {
        setProcessed(true);
    };
    modify ($e2) {
        setProcessed(true);
    };
    FixSpeedEvent fSpeed = new FixSpeedEvent($tId);
    insert(fSpeed);
    System.out.println("Kreiran dogadjaj:       Popravi brzinu reketa!");
end